Malwarebytes\ZendeskBundle\Entity\Comment:
    type: entity
    table: comment
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        zendeskID:
            type: text
            fixed: false
            nullable: true
        body:
            type: text
            fixed: false
            nullable: true
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    manyToOne:
        ticket:
            targetEntity: Ticket
            inversedBy: comments
        author:
            targetEntity: CM\UserBundle\Entity\User
            inversedBy: comments

    lifecycleCallbacks:
        prePersist: [setCreatedValue,setUpdatedValue]
        preUpdate: [setUpdatedValue]