parameters:
    zendesk.apiservice.class: Malwarebytes\ZendeskBundle\Service\ApiService
    zendesk.repositoryservice.class: Malwarebytes\ZendeskBundle\Service\RepositoryService
    zendesk.zendeskservice.class: Malwarebytes\ZendeskBundle\Service\ZendeskService

services:
    zendesk.api:
        class: %zendesk.apiservice.class%
        arguments: [%zendesk_api_key%, %zendesk_api_user%, %zendesk_api_subdomain%]
    zendesk.repos:
        class: %zendesk.repositoryservice.class%
        arguments: [@zendesk.api]
    zendesk.service:
        class: %zendesk.zendeskservice.class%
        arguments: [@zendesk.repos, @fos_user.user_manager.default,@doctrine.orm.entity_manager]
